// Register constants
export const REGISTER_REQUEST = "ACCOUNT_REGISTER_REQUEST"
export const REGISTER_SUCCESS = "ACCOUNT_REGISTER_SUCCESS"
export const REGISTER_ERROR = "ACCOUNT_REGISTER_ERROR"

// Login constants
export const LOGIN_REQUEST = "ACCOUNT_LOGIN_REQUEST"
export const LOGIN_SUCCESS = "ACCOUNT_LOGIN_SUCCESS"
export const LOGIN_ERROR = "ACCOUNT_LOGIN_ERROR"

// Session constants
export const SESSION_LOAD = "ACCOUNT_SESSION_LOAD"
export const SESSION_SUCCESS = "ACCOUNT_SESSION_SUCCESS"
export const SESSION_ERROR = "ACCOUNT_SESSION_ERROR"

// Logout constants
export const LOGOUT = "USERS_LOGOUT"
